version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
      - 443:443
    environment:
      - CHOKIDAR_USEPOLLING=true